### ISSUE TITLE
Write Script to Pull Down Markdown

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-policy-guide-react-component#1]
**Is your feature request related to a problem? Please describe.**
Need to stay consistent with https://github.com/WhiteHouse/source-code-policy

**Describe the solution you'd like**
Bash or node script to pull down markdown files

**Describe alternatives you've considered**
None come to mind except manual labor

**Additional context**
N/A

**Comment by CourtneyBrousseau** [comment]
Closing this issue because this repo has been deprecated
