### ISSUE TITLE
Should link to FSCP

### ISSUE THREAD

**Issue by Karentrebon** [GSA/code-gov-policy-guide-react-component#10]
When you click on section 7.1 (2 places)
https://code.gov/about/open-source/introduction#roles-and-responsibilities   
it doesn’t take you to that section of the policy

**Comment by saracope** [comment]
<img width="824" alt="Screen Shot 2019-05-17 at 12 39 18 PM" src="https://user-images.githubusercontent.com/2197515/57942986-e266d000-78a0-11e9-93cf-894ca43eb3e4.png">

also:
<img width="833" alt="Screen Shot 2019-05-17 at 12 39 13 PM" src="https://user-images.githubusercontent.com/2197515/57942988-e266d000-78a0-11e9-88ac-c5bb9f9ba41a.png">

**Comment by saracope** [comment]
Fixed in https://github.com/GSA/code-gov-about-page/pull/14
