### ISSUE TITLE
Link to Sec 7.7. of policy 

### ISSUE THREAD

**Issue by Karentrebon** [GSA/code-gov-policy-guide-react-component#11]
When you click on Section 7.7 here, it doesn’t take you anywhere:
https://code.gov/about/overview/tracking-progress#accountability-mechanisms

**Comment by saracope** [comment]
<img width="606" alt="Screen Shot 2019-05-17 at 12 38 34 PM" src="https://user-images.githubusercontent.com/2197515/57942928-b6e3e580-78a0-11e9-9fe8-19cc0f4e66b4.png">

**Comment by saracope** [comment]
Fixed in https://github.com/GSA/code-gov-about-page/pull/14
