### ISSUE TITLE
Footnote Color Not Consistent

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-policy-guide-react-component#5]
**Describe the bug**

**To Reproduce**
1. Go to https://code.gov/policy-guide/introduction
2. Scroll down to `These solutions include proprietary, open source, and mixed source2 code...`

**Expected behavior**
Footnote to look like all others

**Screenshots**
![image](https://user-images.githubusercontent.com/4313463/52637184-8dc84900-2e9c-11e9-89fc-7629a12d0ea9.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] ChromeOS
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**
Issue is with content in this file: https://github.com/GSA/code-gov-fscp-react-component/blob/master/pages/markdown/0-introduction.md

**Comment by CourtneyBrousseau** [comment]
Closing this issue because this repo has been deprecated
