### ISSUE TITLE
Link to Sec 7.4 of policy 

### ISSUE THREAD

**Issue by Karentrebon** [GSA/code-gov-policy-guide-react-component#9]
When you are here and click on Section 7.4, it doesn’t take you anywhere https://code.gov/about/open-source/resources#code-repositories

**Comment by saracope** [comment]
Adding screenshot:
<img width="512" alt="Screen Shot 2019-05-17 at 12 40 34 PM" src="https://user-images.githubusercontent.com/2197515/57943034-fe6a7180-78a0-11e9-8ed3-ffe4fd9c49d8.png">

**Comment by saracope** [comment]
Fixed in https://github.com/GSA/code-gov-about-page/pull/14
